// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtop__Syms.h"


void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp);

void Vtop___024root__trace_chg_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    if (VL_UNLIKELY(!vlSymsp->__Vm_activity)) return;
    // Body
    Vtop___024root__trace_chg_0_sub_0((&vlSymsp->TOP), bufp);
}

void Vtop___024root__trace_chg_0_sub_0(Vtop___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    (void)vlSelf;  // Prevent unused variable warning
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_chg_0_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode + 1);
    // Body
    bufp->chgBit(oldp+0,(vlSelf->reset));
    bufp->chgBit(oldp+1,(vlSelf->clk));
    bufp->chgBit(oldp+2,(vlSelf->is_halted));
    bufp->chgIData(oldp+3,(vlSelf->hit_ratio),32);
    bufp->chgIData(oldp+4,(vlSelf->print_reg[0]),32);
    bufp->chgIData(oldp+5,(vlSelf->print_reg[1]),32);
    bufp->chgIData(oldp+6,(vlSelf->print_reg[2]),32);
    bufp->chgIData(oldp+7,(vlSelf->print_reg[3]),32);
    bufp->chgIData(oldp+8,(vlSelf->print_reg[4]),32);
    bufp->chgIData(oldp+9,(vlSelf->print_reg[5]),32);
    bufp->chgIData(oldp+10,(vlSelf->print_reg[6]),32);
    bufp->chgIData(oldp+11,(vlSelf->print_reg[7]),32);
    bufp->chgIData(oldp+12,(vlSelf->print_reg[8]),32);
    bufp->chgIData(oldp+13,(vlSelf->print_reg[9]),32);
    bufp->chgIData(oldp+14,(vlSelf->print_reg[10]),32);
    bufp->chgIData(oldp+15,(vlSelf->print_reg[11]),32);
    bufp->chgIData(oldp+16,(vlSelf->print_reg[12]),32);
    bufp->chgIData(oldp+17,(vlSelf->print_reg[13]),32);
    bufp->chgIData(oldp+18,(vlSelf->print_reg[14]),32);
    bufp->chgIData(oldp+19,(vlSelf->print_reg[15]),32);
    bufp->chgIData(oldp+20,(vlSelf->print_reg[16]),32);
    bufp->chgIData(oldp+21,(vlSelf->print_reg[17]),32);
    bufp->chgIData(oldp+22,(vlSelf->print_reg[18]),32);
    bufp->chgIData(oldp+23,(vlSelf->print_reg[19]),32);
    bufp->chgIData(oldp+24,(vlSelf->print_reg[20]),32);
    bufp->chgIData(oldp+25,(vlSelf->print_reg[21]),32);
    bufp->chgIData(oldp+26,(vlSelf->print_reg[22]),32);
    bufp->chgIData(oldp+27,(vlSelf->print_reg[23]),32);
    bufp->chgIData(oldp+28,(vlSelf->print_reg[24]),32);
    bufp->chgIData(oldp+29,(vlSelf->print_reg[25]),32);
    bufp->chgIData(oldp+30,(vlSelf->print_reg[26]),32);
    bufp->chgIData(oldp+31,(vlSelf->print_reg[27]),32);
    bufp->chgIData(oldp+32,(vlSelf->print_reg[28]),32);
    bufp->chgIData(oldp+33,(vlSelf->print_reg[29]),32);
    bufp->chgIData(oldp+34,(vlSelf->print_reg[30]),32);
    bufp->chgIData(oldp+35,(vlSelf->print_reg[31]),32);
    bufp->chgBit(oldp+36,(vlSelf->top__DOT__reset));
    bufp->chgBit(oldp+37,(vlSelf->top__DOT__clk));
    bufp->chgBit(oldp+38,(vlSelf->top__DOT__is_halted));
    bufp->chgIData(oldp+39,(vlSelf->top__DOT__hit_ratio),32);
    bufp->chgIData(oldp+40,(vlSelf->top__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+41,(vlSelf->top__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+42,(vlSelf->top__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+43,(vlSelf->top__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+44,(vlSelf->top__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+45,(vlSelf->top__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+46,(vlSelf->top__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+47,(vlSelf->top__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+48,(vlSelf->top__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+49,(vlSelf->top__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+50,(vlSelf->top__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+51,(vlSelf->top__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+52,(vlSelf->top__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+53,(vlSelf->top__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+54,(vlSelf->top__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+55,(vlSelf->top__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+56,(vlSelf->top__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+57,(vlSelf->top__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+58,(vlSelf->top__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+59,(vlSelf->top__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+60,(vlSelf->top__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+61,(vlSelf->top__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+62,(vlSelf->top__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+63,(vlSelf->top__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+64,(vlSelf->top__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+65,(vlSelf->top__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+66,(vlSelf->top__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+67,(vlSelf->top__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+68,(vlSelf->top__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+69,(vlSelf->top__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+70,(vlSelf->top__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+71,(vlSelf->top__DOT__print_reg[31]),32);
    bufp->chgBit(oldp+72,(vlSelf->top__DOT__cpu__DOT__reset));
    bufp->chgBit(oldp+73,(vlSelf->top__DOT__cpu__DOT__clk));
    bufp->chgBit(oldp+74,(vlSelf->top__DOT__cpu__DOT__is_halted));
    bufp->chgIData(oldp+75,(vlSelf->top__DOT__cpu__DOT__hit_ratio),32);
    bufp->chgIData(oldp+76,(vlSelf->top__DOT__cpu__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+77,(vlSelf->top__DOT__cpu__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+78,(vlSelf->top__DOT__cpu__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+79,(vlSelf->top__DOT__cpu__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+80,(vlSelf->top__DOT__cpu__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+81,(vlSelf->top__DOT__cpu__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+82,(vlSelf->top__DOT__cpu__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+83,(vlSelf->top__DOT__cpu__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+84,(vlSelf->top__DOT__cpu__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+85,(vlSelf->top__DOT__cpu__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+86,(vlSelf->top__DOT__cpu__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+87,(vlSelf->top__DOT__cpu__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+88,(vlSelf->top__DOT__cpu__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+89,(vlSelf->top__DOT__cpu__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+90,(vlSelf->top__DOT__cpu__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+91,(vlSelf->top__DOT__cpu__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+92,(vlSelf->top__DOT__cpu__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+93,(vlSelf->top__DOT__cpu__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+94,(vlSelf->top__DOT__cpu__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+95,(vlSelf->top__DOT__cpu__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+96,(vlSelf->top__DOT__cpu__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+97,(vlSelf->top__DOT__cpu__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+98,(vlSelf->top__DOT__cpu__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+99,(vlSelf->top__DOT__cpu__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+100,(vlSelf->top__DOT__cpu__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+101,(vlSelf->top__DOT__cpu__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+102,(vlSelf->top__DOT__cpu__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+103,(vlSelf->top__DOT__cpu__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+104,(vlSelf->top__DOT__cpu__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+105,(vlSelf->top__DOT__cpu__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+106,(vlSelf->top__DOT__cpu__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+107,(vlSelf->top__DOT__cpu__DOT__print_reg[31]),32);
    bufp->chgIData(oldp+108,(vlSelf->top__DOT__cpu__DOT__curr_pc),32);
    bufp->chgIData(oldp+109,(vlSelf->top__DOT__cpu__DOT__next_pc),32);
    bufp->chgIData(oldp+110,(vlSelf->top__DOT__cpu__DOT__pc_add4),32);
    bufp->chgIData(oldp+111,(vlSelf->top__DOT__cpu__DOT__pc_addr),32);
    bufp->chgIData(oldp+112,(vlSelf->top__DOT__cpu__DOT__pc_btb),32);
    bufp->chgIData(oldp+113,(vlSelf->top__DOT__cpu__DOT__pc_src1),32);
    bufp->chgIData(oldp+114,(vlSelf->top__DOT__cpu__DOT__pc_src2),32);
    bufp->chgIData(oldp+115,(vlSelf->top__DOT__cpu__DOT__inst),32);
    bufp->chgIData(oldp+116,(vlSelf->top__DOT__cpu__DOT__target_addr),32);
    bufp->chgIData(oldp+117,(vlSelf->top__DOT__cpu__DOT__predicted_target),32);
    bufp->chgCData(oldp+118,(vlSelf->top__DOT__cpu__DOT__PCSrc3),2);
    bufp->chgBit(oldp+119,(vlSelf->top__DOT__cpu__DOT__pcwrite));
    bufp->chgBit(oldp+120,(vlSelf->top__DOT__cpu__DOT__if_id_write));
    bufp->chgBit(oldp+121,(vlSelf->top__DOT__cpu__DOT__control_mux));
    bufp->chgBit(oldp+122,(vlSelf->top__DOT__cpu__DOT__valid));
    bufp->chgBit(oldp+123,(vlSelf->top__DOT__cpu__DOT__taken));
    bufp->chgBit(oldp+124,(vlSelf->top__DOT__cpu__DOT__hit));
    bufp->chgBit(oldp+125,(vlSelf->top__DOT__cpu__DOT__predict_reset));
    bufp->chgBit(oldp+126,(vlSelf->top__DOT__cpu__DOT__prediction));
    bufp->chgBit(oldp+127,(vlSelf->top__DOT__cpu__DOT__jal));
    bufp->chgBit(oldp+128,(vlSelf->top__DOT__cpu__DOT__jalr));
    bufp->chgBit(oldp+129,(vlSelf->top__DOT__cpu__DOT__branch));
    bufp->chgBit(oldp+130,(vlSelf->top__DOT__cpu__DOT__pc_to_reg));
    bufp->chgBit(oldp+131,(vlSelf->top__DOT__cpu__DOT__PCSrc1));
    bufp->chgBit(oldp+132,(vlSelf->top__DOT__cpu__DOT__mem_read));
    bufp->chgBit(oldp+133,(vlSelf->top__DOT__cpu__DOT__mem_to_reg));
    bufp->chgBit(oldp+134,(vlSelf->top__DOT__cpu__DOT__mem_write));
    bufp->chgBit(oldp+135,(vlSelf->top__DOT__cpu__DOT__alu_src));
    bufp->chgBit(oldp+136,(vlSelf->top__DOT__cpu__DOT__write_enable));
    bufp->chgBit(oldp+137,(vlSelf->top__DOT__cpu__DOT__is_ecall));
    bufp->chgBit(oldp+138,(vlSelf->top__DOT__cpu__DOT__bcond));
    bufp->chgCData(oldp+139,(vlSelf->top__DOT__cpu__DOT__alu_op),2);
    bufp->chgIData(oldp+140,(vlSelf->top__DOT__cpu__DOT__write_data),32);
    bufp->chgIData(oldp+141,(vlSelf->top__DOT__cpu__DOT__rs1_dout),32);
    bufp->chgIData(oldp+142,(vlSelf->top__DOT__cpu__DOT__rs2_dout),32);
    bufp->chgIData(oldp+143,(vlSelf->top__DOT__cpu__DOT__imm_gen_out),32);
    bufp->chgSData(oldp+144,(vlSelf->top__DOT__cpu__DOT__control_output),12);
    bufp->chgIData(oldp+145,(vlSelf->top__DOT__cpu__DOT__alu_in_1),32);
    bufp->chgIData(oldp+146,(vlSelf->top__DOT__cpu__DOT__alu_in_2),32);
    bufp->chgIData(oldp+147,(vlSelf->top__DOT__cpu__DOT__alu_src2_out),32);
    bufp->chgIData(oldp+148,(vlSelf->top__DOT__cpu__DOT__alu_result),32);
    bufp->chgCData(oldp+149,(vlSelf->top__DOT__cpu__DOT__alu_control),4);
    bufp->chgCData(oldp+150,(vlSelf->top__DOT__cpu__DOT__foward_A),2);
    bufp->chgCData(oldp+151,(vlSelf->top__DOT__cpu__DOT__foward_B),2);
    bufp->chgIData(oldp+152,(vlSelf->top__DOT__cpu__DOT__mem_dout),32);
    bufp->chgIData(oldp+153,(vlSelf->top__DOT__cpu__DOT__wb_dout),32);
    bufp->chgBit(oldp+154,(vlSelf->top__DOT__cpu__DOT__is_input_valid));
    bufp->chgBit(oldp+155,(vlSelf->top__DOT__cpu__DOT__is_ready));
    bufp->chgBit(oldp+156,(vlSelf->top__DOT__cpu__DOT__is_output_valid));
    bufp->chgBit(oldp+157,(vlSelf->top__DOT__cpu__DOT__is_hit));
    bufp->chgBit(oldp+158,(vlSelf->top__DOT__cpu__DOT__mem_access_stall));
    bufp->chgBit(oldp+159,(vlSelf->top__DOT__cpu__DOT__active_mem_stage));
    bufp->chgIData(oldp+160,(vlSelf->top__DOT__cpu__DOT__IF_ID_inst),32);
    bufp->chgIData(oldp+161,(vlSelf->top__DOT__cpu__DOT__IF_ID_pc),32);
    bufp->chgIData(oldp+162,(vlSelf->top__DOT__cpu__DOT__IF_ID_pc4),32);
    bufp->chgBit(oldp+163,(vlSelf->top__DOT__cpu__DOT__IF_ID_prediction));
    bufp->chgCData(oldp+164,(vlSelf->top__DOT__cpu__DOT__ID_EX_alu_op),2);
    bufp->chgBit(oldp+165,(vlSelf->top__DOT__cpu__DOT__ID_EX_alu_src));
    bufp->chgBit(oldp+166,(vlSelf->top__DOT__cpu__DOT__ID_EX_mem_write));
    bufp->chgBit(oldp+167,(vlSelf->top__DOT__cpu__DOT__ID_EX_mem_read));
    bufp->chgBit(oldp+168,(vlSelf->top__DOT__cpu__DOT__ID_EX_mem_to_reg));
    bufp->chgBit(oldp+169,(vlSelf->top__DOT__cpu__DOT__ID_EX_reg_write));
    bufp->chgBit(oldp+170,(vlSelf->top__DOT__cpu__DOT__ID_EX_jal));
    bufp->chgBit(oldp+171,(vlSelf->top__DOT__cpu__DOT__ID_EX_jalr));
    bufp->chgBit(oldp+172,(vlSelf->top__DOT__cpu__DOT__ID_EX_branch));
    bufp->chgBit(oldp+173,(vlSelf->top__DOT__cpu__DOT__ID_EX_pc_ro_reg));
    bufp->chgBit(oldp+174,(vlSelf->top__DOT__cpu__DOT__ID_EX_is_ecall));
    bufp->chgIData(oldp+175,(vlSelf->top__DOT__cpu__DOT__ID_EX_rs1_data),32);
    bufp->chgIData(oldp+176,(vlSelf->top__DOT__cpu__DOT__ID_EX_rs2_data),32);
    bufp->chgIData(oldp+177,(vlSelf->top__DOT__cpu__DOT__ID_EX_imm),32);
    bufp->chgIData(oldp+178,(vlSelf->top__DOT__cpu__DOT__ID_EX_pc),32);
    bufp->chgIData(oldp+179,(vlSelf->top__DOT__cpu__DOT__ID_EX_pc4),32);
    bufp->chgCData(oldp+180,(vlSelf->top__DOT__cpu__DOT__ID_EX_ALU_ctrl_unit_input),4);
    bufp->chgCData(oldp+181,(vlSelf->top__DOT__cpu__DOT__ID_EX_rs1),5);
    bufp->chgCData(oldp+182,(vlSelf->top__DOT__cpu__DOT__ID_EX_rs2),5);
    bufp->chgCData(oldp+183,(vlSelf->top__DOT__cpu__DOT__ID_EX_rd),5);
    bufp->chgBit(oldp+184,(vlSelf->top__DOT__cpu__DOT__ID_EX_prediction));
    bufp->chgBit(oldp+185,(vlSelf->top__DOT__cpu__DOT__EX_MEM_mem_write));
    bufp->chgBit(oldp+186,(vlSelf->top__DOT__cpu__DOT__EX_MEM_mem_read));
    bufp->chgBit(oldp+187,(vlSelf->top__DOT__cpu__DOT__EX_MEM_is_branch));
    bufp->chgBit(oldp+188,(vlSelf->top__DOT__cpu__DOT__EX_MEM_mem_to_reg));
    bufp->chgBit(oldp+189,(vlSelf->top__DOT__cpu__DOT__EX_MEM_reg_write));
    bufp->chgBit(oldp+190,(vlSelf->top__DOT__cpu__DOT__EX_MEM_is_ecall));
    bufp->chgBit(oldp+191,(vlSelf->top__DOT__cpu__DOT__EX_MEM_pc_to_reg));
    bufp->chgIData(oldp+192,(vlSelf->top__DOT__cpu__DOT__EX_MEM_alu_out),32);
    bufp->chgIData(oldp+193,(vlSelf->top__DOT__cpu__DOT__EX_MEM_dmem_data),32);
    bufp->chgIData(oldp+194,(vlSelf->top__DOT__cpu__DOT__EX_MEM_pc4),32);
    bufp->chgCData(oldp+195,(vlSelf->top__DOT__cpu__DOT__EX_MEM_rd),5);
    bufp->chgBit(oldp+196,(vlSelf->top__DOT__cpu__DOT__MEM_WB_mem_to_reg));
    bufp->chgBit(oldp+197,(vlSelf->top__DOT__cpu__DOT__MEM_WB_reg_write));
    bufp->chgBit(oldp+198,(vlSelf->top__DOT__cpu__DOT__MEM_WB_is_ecall));
    bufp->chgBit(oldp+199,(vlSelf->top__DOT__cpu__DOT__MEM_WB_pc_to_reg));
    bufp->chgIData(oldp+200,(vlSelf->top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_0),32);
    bufp->chgIData(oldp+201,(vlSelf->top__DOT__cpu__DOT__MEM_WB_mem_to_reg_src_1),32);
    bufp->chgIData(oldp+202,(vlSelf->top__DOT__cpu__DOT__MEM_WB_pc4),32);
    bufp->chgCData(oldp+203,(vlSelf->top__DOT__cpu__DOT__MEM_WB_rd),5);
    bufp->chgCData(oldp+204,(vlSelf->top__DOT__cpu__DOT__ALUSRC1__DOT__S),2);
    bufp->chgIData(oldp+205,(vlSelf->top__DOT__cpu__DOT__ALUSRC1__DOT__D0),32);
    bufp->chgIData(oldp+206,(vlSelf->top__DOT__cpu__DOT__ALUSRC1__DOT__D1),32);
    bufp->chgIData(oldp+207,(vlSelf->top__DOT__cpu__DOT__ALUSRC1__DOT__D2),32);
    bufp->chgIData(oldp+208,(vlSelf->top__DOT__cpu__DOT__ALUSRC1__DOT__D3),32);
    bufp->chgIData(oldp+209,(vlSelf->top__DOT__cpu__DOT__ALUSRC1__DOT__Y),32);
    bufp->chgCData(oldp+210,(vlSelf->top__DOT__cpu__DOT__ALUSRC2__DOT__S),2);
    bufp->chgIData(oldp+211,(vlSelf->top__DOT__cpu__DOT__ALUSRC2__DOT__D0),32);
    bufp->chgIData(oldp+212,(vlSelf->top__DOT__cpu__DOT__ALUSRC2__DOT__D1),32);
    bufp->chgIData(oldp+213,(vlSelf->top__DOT__cpu__DOT__ALUSRC2__DOT__D2),32);
    bufp->chgIData(oldp+214,(vlSelf->top__DOT__cpu__DOT__ALUSRC2__DOT__D3),32);
    bufp->chgIData(oldp+215,(vlSelf->top__DOT__cpu__DOT__ALUSRC2__DOT__Y),32);
    bufp->chgBit(oldp+216,(vlSelf->top__DOT__cpu__DOT__ALUSRC_IMM__DOT__S));
    bufp->chgIData(oldp+217,(vlSelf->top__DOT__cpu__DOT__ALUSRC_IMM__DOT__D0),32);
    bufp->chgIData(oldp+218,(vlSelf->top__DOT__cpu__DOT__ALUSRC_IMM__DOT__D1),32);
    bufp->chgIData(oldp+219,(vlSelf->top__DOT__cpu__DOT__ALUSRC_IMM__DOT__Y),32);
    bufp->chgBit(oldp+220,(vlSelf->top__DOT__cpu__DOT__BTB__DOT__S));
    bufp->chgIData(oldp+221,(vlSelf->top__DOT__cpu__DOT__BTB__DOT__D0),32);
    bufp->chgIData(oldp+222,(vlSelf->top__DOT__cpu__DOT__BTB__DOT__D1),32);
    bufp->chgIData(oldp+223,(vlSelf->top__DOT__cpu__DOT__BTB__DOT__Y),32);
    bufp->chgBit(oldp+224,(vlSelf->top__DOT__cpu__DOT__PCS1__DOT__S));
    bufp->chgIData(oldp+225,(vlSelf->top__DOT__cpu__DOT__PCS1__DOT__D0),32);
    bufp->chgIData(oldp+226,(vlSelf->top__DOT__cpu__DOT__PCS1__DOT__D1),32);
    bufp->chgIData(oldp+227,(vlSelf->top__DOT__cpu__DOT__PCS1__DOT__Y),32);
    bufp->chgBit(oldp+228,(vlSelf->top__DOT__cpu__DOT__PCS2__DOT__S));
    bufp->chgIData(oldp+229,(vlSelf->top__DOT__cpu__DOT__PCS2__DOT__D0),32);
    bufp->chgIData(oldp+230,(vlSelf->top__DOT__cpu__DOT__PCS2__DOT__D1),32);
    bufp->chgIData(oldp+231,(vlSelf->top__DOT__cpu__DOT__PCS2__DOT__Y),32);
    bufp->chgBit(oldp+232,(vlSelf->top__DOT__cpu__DOT__WBSRC__DOT__S));
    bufp->chgIData(oldp+233,(vlSelf->top__DOT__cpu__DOT__WBSRC__DOT__D0),32);
    bufp->chgIData(oldp+234,(vlSelf->top__DOT__cpu__DOT__WBSRC__DOT__D1),32);
    bufp->chgIData(oldp+235,(vlSelf->top__DOT__cpu__DOT__WBSRC__DOT__Y),32);
    bufp->chgBit(oldp+236,(vlSelf->top__DOT__cpu__DOT__Write_Data__DOT__S));
    bufp->chgIData(oldp+237,(vlSelf->top__DOT__cpu__DOT__Write_Data__DOT__D0),32);
    bufp->chgIData(oldp+238,(vlSelf->top__DOT__cpu__DOT__Write_Data__DOT__D1),32);
    bufp->chgIData(oldp+239,(vlSelf->top__DOT__cpu__DOT__Write_Data__DOT__Y),32);
    bufp->chgIData(oldp+240,(vlSelf->top__DOT__cpu__DOT__add4_PC__DOT__alu_in_1),32);
    bufp->chgIData(oldp+241,(vlSelf->top__DOT__cpu__DOT__add4_PC__DOT__alu_in_2),32);
    bufp->chgIData(oldp+242,(vlSelf->top__DOT__cpu__DOT__add4_PC__DOT__alu_result),32);
    bufp->chgIData(oldp+243,(vlSelf->top__DOT__cpu__DOT__addr_PC__DOT__alu_in_1),32);
    bufp->chgIData(oldp+244,(vlSelf->top__DOT__cpu__DOT__addr_PC__DOT__alu_in_2),32);
    bufp->chgIData(oldp+245,(vlSelf->top__DOT__cpu__DOT__addr_PC__DOT__alu_result),32);
    bufp->chgIData(oldp+246,(vlSelf->top__DOT__cpu__DOT__alu__DOT__in_1),32);
    bufp->chgIData(oldp+247,(vlSelf->top__DOT__cpu__DOT__alu__DOT__in_2),32);
    bufp->chgCData(oldp+248,(vlSelf->top__DOT__cpu__DOT__alu__DOT__control),4);
    bufp->chgBit(oldp+249,(vlSelf->top__DOT__cpu__DOT__alu__DOT__bcond));
    bufp->chgIData(oldp+250,(vlSelf->top__DOT__cpu__DOT__alu__DOT__result),32);
    bufp->chgCData(oldp+251,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__part_of_inst),4);
    bufp->chgCData(oldp+252,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_op),2);
    bufp->chgCData(oldp+253,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__alu_control),4);
    bufp->chgBit(oldp+254,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__sub_or_not));
    bufp->chgCData(oldp+255,(vlSelf->top__DOT__cpu__DOT__alu_ctrl_unit__DOT__funct3),3);
    bufp->chgBit(oldp+256,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__clk));
    bufp->chgBit(oldp+257,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__reset));
    bufp->chgIData(oldp+258,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pc_addr),32);
    bufp->chgBit(oldp+259,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__valid));
    bufp->chgBit(oldp+260,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__taken));
    bufp->chgIData(oldp+261,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__ex_addr),32);
    bufp->chgIData(oldp+262,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__target_addr),32);
    bufp->chgBit(oldp+263,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__hit));
    bufp->chgBit(oldp+264,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__prediction));
    bufp->chgIData(oldp+265,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__predicted_target),32);
    bufp->chgIData(oldp+266,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[0]),32);
    bufp->chgIData(oldp+267,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[1]),32);
    bufp->chgIData(oldp+268,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[2]),32);
    bufp->chgIData(oldp+269,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[3]),32);
    bufp->chgIData(oldp+270,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[4]),32);
    bufp->chgIData(oldp+271,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[5]),32);
    bufp->chgIData(oldp+272,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[6]),32);
    bufp->chgIData(oldp+273,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[7]),32);
    bufp->chgIData(oldp+274,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[8]),32);
    bufp->chgIData(oldp+275,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[9]),32);
    bufp->chgIData(oldp+276,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[10]),32);
    bufp->chgIData(oldp+277,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[11]),32);
    bufp->chgIData(oldp+278,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[12]),32);
    bufp->chgIData(oldp+279,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[13]),32);
    bufp->chgIData(oldp+280,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[14]),32);
    bufp->chgIData(oldp+281,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[15]),32);
    bufp->chgIData(oldp+282,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[16]),32);
    bufp->chgIData(oldp+283,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[17]),32);
    bufp->chgIData(oldp+284,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[18]),32);
    bufp->chgIData(oldp+285,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[19]),32);
    bufp->chgIData(oldp+286,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[20]),32);
    bufp->chgIData(oldp+287,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[21]),32);
    bufp->chgIData(oldp+288,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[22]),32);
    bufp->chgIData(oldp+289,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[23]),32);
    bufp->chgIData(oldp+290,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[24]),32);
    bufp->chgIData(oldp+291,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[25]),32);
    bufp->chgIData(oldp+292,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[26]),32);
    bufp->chgIData(oldp+293,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[27]),32);
    bufp->chgIData(oldp+294,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[28]),32);
    bufp->chgIData(oldp+295,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[29]),32);
    bufp->chgIData(oldp+296,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[30]),32);
    bufp->chgIData(oldp+297,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__btb_table[31]),32);
    bufp->chgIData(oldp+298,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[0]),25);
    bufp->chgIData(oldp+299,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[1]),25);
    bufp->chgIData(oldp+300,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[2]),25);
    bufp->chgIData(oldp+301,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[3]),25);
    bufp->chgIData(oldp+302,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[4]),25);
    bufp->chgIData(oldp+303,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[5]),25);
    bufp->chgIData(oldp+304,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[6]),25);
    bufp->chgIData(oldp+305,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[7]),25);
    bufp->chgIData(oldp+306,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[8]),25);
    bufp->chgIData(oldp+307,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[9]),25);
    bufp->chgIData(oldp+308,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[10]),25);
    bufp->chgIData(oldp+309,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[11]),25);
    bufp->chgIData(oldp+310,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[12]),25);
    bufp->chgIData(oldp+311,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[13]),25);
    bufp->chgIData(oldp+312,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[14]),25);
    bufp->chgIData(oldp+313,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[15]),25);
    bufp->chgIData(oldp+314,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[16]),25);
    bufp->chgIData(oldp+315,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[17]),25);
    bufp->chgIData(oldp+316,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[18]),25);
    bufp->chgIData(oldp+317,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[19]),25);
    bufp->chgIData(oldp+318,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[20]),25);
    bufp->chgIData(oldp+319,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[21]),25);
    bufp->chgIData(oldp+320,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[22]),25);
    bufp->chgIData(oldp+321,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[23]),25);
    bufp->chgIData(oldp+322,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[24]),25);
    bufp->chgIData(oldp+323,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[25]),25);
    bufp->chgIData(oldp+324,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[26]),25);
    bufp->chgIData(oldp+325,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[27]),25);
    bufp->chgIData(oldp+326,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[28]),25);
    bufp->chgIData(oldp+327,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[29]),25);
    bufp->chgIData(oldp+328,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[30]),25);
    bufp->chgIData(oldp+329,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag_table[31]),25);
    bufp->chgCData(oldp+330,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[0]),2);
    bufp->chgCData(oldp+331,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[1]),2);
    bufp->chgCData(oldp+332,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[2]),2);
    bufp->chgCData(oldp+333,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[3]),2);
    bufp->chgCData(oldp+334,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[4]),2);
    bufp->chgCData(oldp+335,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[5]),2);
    bufp->chgCData(oldp+336,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[6]),2);
    bufp->chgCData(oldp+337,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[7]),2);
    bufp->chgCData(oldp+338,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[8]),2);
    bufp->chgCData(oldp+339,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[9]),2);
    bufp->chgCData(oldp+340,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[10]),2);
    bufp->chgCData(oldp+341,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[11]),2);
    bufp->chgCData(oldp+342,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[12]),2);
    bufp->chgCData(oldp+343,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[13]),2);
    bufp->chgCData(oldp+344,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[14]),2);
    bufp->chgCData(oldp+345,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[15]),2);
    bufp->chgCData(oldp+346,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[16]),2);
    bufp->chgCData(oldp+347,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[17]),2);
    bufp->chgCData(oldp+348,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[18]),2);
    bufp->chgCData(oldp+349,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[19]),2);
    bufp->chgCData(oldp+350,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[20]),2);
    bufp->chgCData(oldp+351,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[21]),2);
    bufp->chgCData(oldp+352,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[22]),2);
    bufp->chgCData(oldp+353,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[23]),2);
    bufp->chgCData(oldp+354,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[24]),2);
    bufp->chgCData(oldp+355,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[25]),2);
    bufp->chgCData(oldp+356,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[26]),2);
    bufp->chgCData(oldp+357,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[27]),2);
    bufp->chgCData(oldp+358,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[28]),2);
    bufp->chgCData(oldp+359,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[29]),2);
    bufp->chgCData(oldp+360,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[30]),2);
    bufp->chgCData(oldp+361,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht[31]),2);
    bufp->chgCData(oldp+362,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__index),5);
    bufp->chgIData(oldp+363,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__tag),25);
    bufp->chgCData(oldp+364,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__exidx),5);
    bufp->chgIData(oldp+365,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__extag),25);
    bufp->chgCData(oldp+366,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__pht_idx),5);
    bufp->chgCData(oldp+367,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__BHSR),5);
    bufp->chgIData(oldp+368,(vlSelf->top__DOT__cpu__DOT__branchpredictor__DOT__i),32);
    bufp->chgBit(oldp+369,(vlSelf->top__DOT__cpu__DOT__cache__DOT__reset));
    bufp->chgBit(oldp+370,(vlSelf->top__DOT__cpu__DOT__cache__DOT__clk));
    bufp->chgBit(oldp+371,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_input_valid));
    bufp->chgIData(oldp+372,(vlSelf->top__DOT__cpu__DOT__cache__DOT__addr),32);
    bufp->chgBit(oldp+373,(vlSelf->top__DOT__cpu__DOT__cache__DOT__mem_rw));
    bufp->chgIData(oldp+374,(vlSelf->top__DOT__cpu__DOT__cache__DOT__din),32);
    bufp->chgBit(oldp+375,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_ready));
    bufp->chgBit(oldp+376,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_output_valid));
    bufp->chgIData(oldp+377,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dout),32);
    bufp->chgBit(oldp+378,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_hit));
    bufp->chgIData(oldp+379,(vlSelf->top__DOT__cpu__DOT__cache__DOT__hit_ratio),32);
    bufp->chgIData(oldp+380,(vlSelf->top__DOT__cpu__DOT__cache__DOT__total_accesses),32);
    bufp->chgIData(oldp+381,(vlSelf->top__DOT__cpu__DOT__cache__DOT__miss_count),32);
    bufp->chgIData(oldp+382,(vlSelf->top__DOT__cpu__DOT__cache__DOT__input_tag),26);
    bufp->chgCData(oldp+383,(vlSelf->top__DOT__cpu__DOT__cache__DOT__set_index),2);
    bufp->chgCData(oldp+384,(vlSelf->top__DOT__cpu__DOT__cache__DOT__block_offset),2);
    bufp->chgCData(oldp+385,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [0U][0U]),3);
    bufp->chgCData(oldp+386,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [0U][1U]),3);
    bufp->chgCData(oldp+387,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [0U][2U]),3);
    bufp->chgCData(oldp+388,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [0U][3U]),3);
    bufp->chgCData(oldp+389,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [1U][0U]),3);
    bufp->chgCData(oldp+390,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [1U][1U]),3);
    bufp->chgCData(oldp+391,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [1U][2U]),3);
    bufp->chgCData(oldp+392,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [1U][3U]),3);
    bufp->chgCData(oldp+393,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [2U][0U]),3);
    bufp->chgCData(oldp+394,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [2U][1U]),3);
    bufp->chgCData(oldp+395,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [2U][2U]),3);
    bufp->chgCData(oldp+396,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [2U][3U]),3);
    bufp->chgCData(oldp+397,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [3U][0U]),3);
    bufp->chgCData(oldp+398,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [3U][1U]),3);
    bufp->chgCData(oldp+399,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [3U][2U]),3);
    bufp->chgCData(oldp+400,(vlSelf->top__DOT__cpu__DOT__cache__DOT__lru
                             [3U][3U]),3);
    bufp->chgBit(oldp+401,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [0U][0U]));
    bufp->chgBit(oldp+402,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [0U][1U]));
    bufp->chgBit(oldp+403,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [0U][2U]));
    bufp->chgBit(oldp+404,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [0U][3U]));
    bufp->chgBit(oldp+405,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [1U][0U]));
    bufp->chgBit(oldp+406,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [1U][1U]));
    bufp->chgBit(oldp+407,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [1U][2U]));
    bufp->chgBit(oldp+408,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [1U][3U]));
    bufp->chgBit(oldp+409,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [2U][0U]));
    bufp->chgBit(oldp+410,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [2U][1U]));
    bufp->chgBit(oldp+411,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [2U][2U]));
    bufp->chgBit(oldp+412,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [2U][3U]));
    bufp->chgBit(oldp+413,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [3U][0U]));
    bufp->chgBit(oldp+414,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [3U][1U]));
    bufp->chgBit(oldp+415,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [3U][2U]));
    bufp->chgBit(oldp+416,(vlSelf->top__DOT__cpu__DOT__cache__DOT__dirty
                           [3U][3U]));
    bufp->chgBit(oldp+417,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [0U][0U]));
    bufp->chgBit(oldp+418,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [0U][1U]));
    bufp->chgBit(oldp+419,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [0U][2U]));
    bufp->chgBit(oldp+420,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [0U][3U]));
    bufp->chgBit(oldp+421,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [1U][0U]));
    bufp->chgBit(oldp+422,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [1U][1U]));
    bufp->chgBit(oldp+423,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [1U][2U]));
    bufp->chgBit(oldp+424,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [1U][3U]));
    bufp->chgBit(oldp+425,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [2U][0U]));
    bufp->chgBit(oldp+426,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [2U][1U]));
    bufp->chgBit(oldp+427,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [2U][2U]));
    bufp->chgBit(oldp+428,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [2U][3U]));
    bufp->chgBit(oldp+429,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [3U][0U]));
    bufp->chgBit(oldp+430,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [3U][1U]));
    bufp->chgBit(oldp+431,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [3U][2U]));
    bufp->chgBit(oldp+432,(vlSelf->top__DOT__cpu__DOT__cache__DOT__valid
                           [3U][3U]));
    bufp->chgIData(oldp+433,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [0U][0U]),26);
    bufp->chgIData(oldp+434,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [0U][1U]),26);
    bufp->chgIData(oldp+435,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [0U][2U]),26);
    bufp->chgIData(oldp+436,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [0U][3U]),26);
    bufp->chgIData(oldp+437,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [1U][0U]),26);
    bufp->chgIData(oldp+438,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [1U][1U]),26);
    bufp->chgIData(oldp+439,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [1U][2U]),26);
    bufp->chgIData(oldp+440,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [1U][3U]),26);
    bufp->chgIData(oldp+441,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [2U][0U]),26);
    bufp->chgIData(oldp+442,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [2U][1U]),26);
    bufp->chgIData(oldp+443,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [2U][2U]),26);
    bufp->chgIData(oldp+444,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [2U][3U]),26);
    bufp->chgIData(oldp+445,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [3U][0U]),26);
    bufp->chgIData(oldp+446,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [3U][1U]),26);
    bufp->chgIData(oldp+447,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [3U][2U]),26);
    bufp->chgIData(oldp+448,(vlSelf->top__DOT__cpu__DOT__cache__DOT__tag
                             [3U][3U]),26);
    bufp->chgWData(oldp+449,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [0U][0U]),128);
    bufp->chgWData(oldp+453,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [0U][1U]),128);
    bufp->chgWData(oldp+457,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [0U][2U]),128);
    bufp->chgWData(oldp+461,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [0U][3U]),128);
    bufp->chgWData(oldp+465,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [1U][0U]),128);
    bufp->chgWData(oldp+469,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [1U][1U]),128);
    bufp->chgWData(oldp+473,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [1U][2U]),128);
    bufp->chgWData(oldp+477,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [1U][3U]),128);
    bufp->chgWData(oldp+481,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [2U][0U]),128);
    bufp->chgWData(oldp+485,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [2U][1U]),128);
    bufp->chgWData(oldp+489,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [2U][2U]),128);
    bufp->chgWData(oldp+493,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [2U][3U]),128);
    bufp->chgWData(oldp+497,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [3U][0U]),128);
    bufp->chgWData(oldp+501,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [3U][1U]),128);
    bufp->chgWData(oldp+505,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [3U][2U]),128);
    bufp->chgWData(oldp+509,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data
                             [3U][3U]),128);
    bufp->chgIData(oldp+513,(vlSelf->top__DOT__cpu__DOT__cache__DOT__i),32);
    bufp->chgIData(oldp+514,(vlSelf->top__DOT__cpu__DOT__cache__DOT__j),32);
    bufp->chgCData(oldp+515,(vlSelf->top__DOT__cpu__DOT__cache__DOT__state),2);
    bufp->chgIData(oldp+516,(vlSelf->top__DOT__cpu__DOT__cache__DOT__m),32);
    bufp->chgCData(oldp+517,(vlSelf->top__DOT__cpu__DOT__cache__DOT__check_hit_index),3);
    bufp->chgCData(oldp+518,(vlSelf->top__DOT__cpu__DOT__cache__DOT__check_change_index),3);
    bufp->chgCData(oldp+519,(vlSelf->top__DOT__cpu__DOT__cache__DOT__hit_index),2);
    bufp->chgCData(oldp+520,(vlSelf->top__DOT__cpu__DOT__cache__DOT__change_index),2);
    bufp->chgBit(oldp+521,(vlSelf->top__DOT__cpu__DOT__cache__DOT__all_valid));
    bufp->chgIData(oldp+522,(vlSelf->top__DOT__cpu__DOT__cache__DOT__k),32);
    bufp->chgIData(oldp+523,(vlSelf->top__DOT__cpu__DOT__cache__DOT__l),32);
    bufp->chgWData(oldp+524,(vlSelf->top__DOT__cpu__DOT__cache__DOT__mem_din),128);
    bufp->chgWData(oldp+528,(vlSelf->top__DOT__cpu__DOT__cache__DOT__mem_dout),128);
    bufp->chgBit(oldp+532,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_mem_input_valid));
    bufp->chgBit(oldp+533,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_mem_output_valid));
    bufp->chgBit(oldp+534,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_data_mem_ready));
    bufp->chgBit(oldp+535,(vlSelf->top__DOT__cpu__DOT__cache__DOT__mem_read));
    bufp->chgBit(oldp+536,(vlSelf->top__DOT__cpu__DOT__cache__DOT__mem_write));
    bufp->chgBit(oldp+537,(vlSelf->top__DOT__cpu__DOT__cache__DOT__is_mem_write_done));
    bufp->chgIData(oldp+538,(vlSelf->top__DOT__cpu__DOT__cache__DOT__write_addr),32);
    bufp->chgBit(oldp+539,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__reset));
    bufp->chgBit(oldp+540,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__clk));
    bufp->chgBit(oldp+541,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_input_valid));
    bufp->chgIData(oldp+542,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__addr),32);
    bufp->chgBit(oldp+543,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_read));
    bufp->chgBit(oldp+544,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_write));
    bufp->chgWData(oldp+545,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__din),128);
    bufp->chgBit(oldp+549,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_output_valid));
    bufp->chgBit(oldp+550,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__is_write_done));
    bufp->chgWData(oldp+551,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__dout),128);
    bufp->chgBit(oldp+555,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__mem_ready));
    bufp->chgIData(oldp+556,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__i),32);
    bufp->chgIData(oldp+557,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__delay_counter),32);
    bufp->chgBit(oldp+558,(vlSelf->top__DOT__cpu__DOT__cache__DOT__data_mem__DOT__request_arrived));
    bufp->chgBit(oldp+559,(vlSelf->top__DOT__cpu__DOT__control_signal__DOT__S));
    bufp->chgSData(oldp+560,(vlSelf->top__DOT__cpu__DOT__control_signal__DOT__D0),12);
    bufp->chgSData(oldp+561,(vlSelf->top__DOT__cpu__DOT__control_signal__DOT__D1),12);
    bufp->chgSData(oldp+562,(vlSelf->top__DOT__cpu__DOT__control_signal__DOT__Y),12);
    bufp->chgCData(oldp+563,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__opcode),7);
    bufp->chgBit(oldp+564,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__is_jal));
    bufp->chgBit(oldp+565,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__is_jalr));
    bufp->chgBit(oldp+566,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__branch));
    bufp->chgBit(oldp+567,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__pc_to_reg));
    bufp->chgBit(oldp+568,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__mem_read));
    bufp->chgBit(oldp+569,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__mem_to_reg));
    bufp->chgBit(oldp+570,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__mem_write));
    bufp->chgBit(oldp+571,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__alu_src));
    bufp->chgBit(oldp+572,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__write_enable));
    bufp->chgCData(oldp+573,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__alu_op),2);
    bufp->chgBit(oldp+574,(vlSelf->top__DOT__cpu__DOT__ctrl_unit__DOT__is_ecall));
    bufp->chgCData(oldp+575,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__ex_mem_rd),5);
    bufp->chgCData(oldp+576,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__mem_wb_rd),5);
    bufp->chgCData(oldp+577,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__rs1),5);
    bufp->chgCData(oldp+578,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__rs2),5);
    bufp->chgBit(oldp+579,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__ex_mem_RW));
    bufp->chgBit(oldp+580,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__mem_wb_RW));
    bufp->chgCData(oldp+581,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__mux_forward_A),2);
    bufp->chgCData(oldp+582,(vlSelf->top__DOT__cpu__DOT__forwarding_unit__DOT__mux_forward_B),2);
    bufp->chgCData(oldp+583,(vlSelf->top__DOT__cpu__DOT__hazard_detectoin_unit__DOT__opcode),7);
    bufp->chgCData(oldp+584,(vlSelf->top__DOT__cpu__DOT__hazard_detectoin_unit__DOT__rs1),5);
    bufp->chgCData(oldp+585,(vlSelf->top__DOT__cpu__DOT__hazard_detectoin_unit__DOT__rs2),5);
    bufp->chgCData(oldp+586,(vlSelf->top__DOT__cpu__DOT__hazard_detectoin_unit__DOT__id_ex_rd),5);
    bufp->chgBit(oldp+587,(vlSelf->top__DOT__cpu__DOT__hazard_detectoin_unit__DOT__id_ex_memread));
    bufp->chgBit(oldp+588,(vlSelf->top__DOT__cpu__DOT__hazard_detectoin_unit__DOT__pcwrite));
    bufp->chgBit(oldp+589,(vlSelf->top__DOT__cpu__DOT__hazard_detectoin_unit__DOT__if_id_write));
    bufp->chgBit(oldp+590,(vlSelf->top__DOT__cpu__DOT__hazard_detectoin_unit__DOT__control_mux));
    bufp->chgBit(oldp+591,(vlSelf->top__DOT__cpu__DOT__hazard_detectoin_unit__DOT__use_rs1));
    bufp->chgBit(oldp+592,(vlSelf->top__DOT__cpu__DOT__hazard_detectoin_unit__DOT__use_rs2));
    bufp->chgBit(oldp+593,(vlSelf->top__DOT__cpu__DOT__imem__DOT__reset));
    bufp->chgBit(oldp+594,(vlSelf->top__DOT__cpu__DOT__imem__DOT__clk));
    bufp->chgIData(oldp+595,(vlSelf->top__DOT__cpu__DOT__imem__DOT__addr),32);
    bufp->chgIData(oldp+596,(vlSelf->top__DOT__cpu__DOT__imem__DOT__dout),32);
    bufp->chgIData(oldp+597,(vlSelf->top__DOT__cpu__DOT__imem__DOT__i),32);
    bufp->chgIData(oldp+598,(vlSelf->top__DOT__cpu__DOT__imem__DOT__imem_addr),32);
    bufp->chgIData(oldp+599,(vlSelf->top__DOT__cpu__DOT__imm_gen__DOT__part_of_inst),32);
    bufp->chgIData(oldp+600,(vlSelf->top__DOT__cpu__DOT__imm_gen__DOT__imm_gen_out),32);
    bufp->chgCData(oldp+601,(vlSelf->top__DOT__cpu__DOT__imm_gen__DOT__funct3),3);
    bufp->chgCData(oldp+602,(vlSelf->top__DOT__cpu__DOT__imm_gen__DOT__opcode),7);
    bufp->chgCData(oldp+603,(vlSelf->top__DOT__cpu__DOT__is_correct__DOT__S),2);
    bufp->chgIData(oldp+604,(vlSelf->top__DOT__cpu__DOT__is_correct__DOT__D0),32);
    bufp->chgIData(oldp+605,(vlSelf->top__DOT__cpu__DOT__is_correct__DOT__D1),32);
    bufp->chgIData(oldp+606,(vlSelf->top__DOT__cpu__DOT__is_correct__DOT__D2),32);
    bufp->chgIData(oldp+607,(vlSelf->top__DOT__cpu__DOT__is_correct__DOT__D3),32);
    bufp->chgIData(oldp+608,(vlSelf->top__DOT__cpu__DOT__is_correct__DOT__Y),32);
    bufp->chgBit(oldp+609,(vlSelf->top__DOT__cpu__DOT__iscorrect__DOT__taken));
    bufp->chgBit(oldp+610,(vlSelf->top__DOT__cpu__DOT__iscorrect__DOT__prediction));
    bufp->chgIData(oldp+611,(vlSelf->top__DOT__cpu__DOT__iscorrect__DOT__cu_pc),32);
    bufp->chgIData(oldp+612,(vlSelf->top__DOT__cpu__DOT__iscorrect__DOT__pre_pc),32);
    bufp->chgCData(oldp+613,(vlSelf->top__DOT__cpu__DOT__iscorrect__DOT__pc_mux_flag),2);
    bufp->chgBit(oldp+614,(vlSelf->top__DOT__cpu__DOT__iscorrect__DOT__predict_reset));
    bufp->chgBit(oldp+615,(vlSelf->top__DOT__cpu__DOT__pc__DOT__reset));
    bufp->chgBit(oldp+616,(vlSelf->top__DOT__cpu__DOT__pc__DOT__clk));
    bufp->chgBit(oldp+617,(vlSelf->top__DOT__cpu__DOT__pc__DOT__pcwrite));
    bufp->chgIData(oldp+618,(vlSelf->top__DOT__cpu__DOT__pc__DOT__next_pc),32);
    bufp->chgIData(oldp+619,(vlSelf->top__DOT__cpu__DOT__pc__DOT__curr_pc),32);
    bufp->chgBit(oldp+620,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__reset));
    bufp->chgBit(oldp+621,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__clk));
    bufp->chgCData(oldp+622,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rs1),5);
    bufp->chgCData(oldp+623,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rs2),5);
    bufp->chgCData(oldp+624,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rd),5);
    bufp->chgIData(oldp+625,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rd_din),32);
    bufp->chgBit(oldp+626,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__write_enable));
    bufp->chgIData(oldp+627,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rs1_dout),32);
    bufp->chgIData(oldp+628,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rs2_dout),32);
    bufp->chgIData(oldp+629,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[0]),32);
    bufp->chgIData(oldp+630,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[1]),32);
    bufp->chgIData(oldp+631,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[2]),32);
    bufp->chgIData(oldp+632,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[3]),32);
    bufp->chgIData(oldp+633,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[4]),32);
    bufp->chgIData(oldp+634,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[5]),32);
    bufp->chgIData(oldp+635,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[6]),32);
    bufp->chgIData(oldp+636,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[7]),32);
    bufp->chgIData(oldp+637,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[8]),32);
    bufp->chgIData(oldp+638,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[9]),32);
    bufp->chgIData(oldp+639,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[10]),32);
    bufp->chgIData(oldp+640,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[11]),32);
    bufp->chgIData(oldp+641,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[12]),32);
    bufp->chgIData(oldp+642,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[13]),32);
    bufp->chgIData(oldp+643,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[14]),32);
    bufp->chgIData(oldp+644,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[15]),32);
    bufp->chgIData(oldp+645,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[16]),32);
    bufp->chgIData(oldp+646,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[17]),32);
    bufp->chgIData(oldp+647,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[18]),32);
    bufp->chgIData(oldp+648,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[19]),32);
    bufp->chgIData(oldp+649,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[20]),32);
    bufp->chgIData(oldp+650,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[21]),32);
    bufp->chgIData(oldp+651,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[22]),32);
    bufp->chgIData(oldp+652,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[23]),32);
    bufp->chgIData(oldp+653,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[24]),32);
    bufp->chgIData(oldp+654,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[25]),32);
    bufp->chgIData(oldp+655,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[26]),32);
    bufp->chgIData(oldp+656,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[27]),32);
    bufp->chgIData(oldp+657,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[28]),32);
    bufp->chgIData(oldp+658,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[29]),32);
    bufp->chgIData(oldp+659,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[30]),32);
    bufp->chgIData(oldp+660,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__print_reg[31]),32);
    bufp->chgIData(oldp+661,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__i),32);
    bufp->chgIData(oldp+662,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[0]),32);
    bufp->chgIData(oldp+663,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[1]),32);
    bufp->chgIData(oldp+664,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[2]),32);
    bufp->chgIData(oldp+665,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[3]),32);
    bufp->chgIData(oldp+666,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[4]),32);
    bufp->chgIData(oldp+667,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[5]),32);
    bufp->chgIData(oldp+668,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[6]),32);
    bufp->chgIData(oldp+669,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[7]),32);
    bufp->chgIData(oldp+670,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[8]),32);
    bufp->chgIData(oldp+671,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[9]),32);
    bufp->chgIData(oldp+672,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[10]),32);
    bufp->chgIData(oldp+673,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[11]),32);
    bufp->chgIData(oldp+674,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[12]),32);
    bufp->chgIData(oldp+675,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[13]),32);
    bufp->chgIData(oldp+676,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[14]),32);
    bufp->chgIData(oldp+677,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[15]),32);
    bufp->chgIData(oldp+678,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[16]),32);
    bufp->chgIData(oldp+679,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[17]),32);
    bufp->chgIData(oldp+680,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[18]),32);
    bufp->chgIData(oldp+681,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[19]),32);
    bufp->chgIData(oldp+682,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[20]),32);
    bufp->chgIData(oldp+683,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[21]),32);
    bufp->chgIData(oldp+684,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[22]),32);
    bufp->chgIData(oldp+685,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[23]),32);
    bufp->chgIData(oldp+686,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[24]),32);
    bufp->chgIData(oldp+687,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[25]),32);
    bufp->chgIData(oldp+688,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[26]),32);
    bufp->chgIData(oldp+689,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[27]),32);
    bufp->chgIData(oldp+690,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[28]),32);
    bufp->chgIData(oldp+691,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[29]),32);
    bufp->chgIData(oldp+692,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[30]),32);
    bufp->chgIData(oldp+693,(vlSelf->top__DOT__cpu__DOT__reg_file__DOT__rf[31]),32);
}

void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_cleanup\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VlUnpacked<CData/*0:0*/, 1> __Vm_traceActivity;
    for (int __Vi0 = 0; __Vi0 < 1; ++__Vi0) {
        __Vm_traceActivity[__Vi0] = 0;
    }
    // Body
    vlSymsp->__Vm_activity = false;
    __Vm_traceActivity[0U] = 0U;
}
